#!/usr/bin/env sh

mode=$1
day=$2
part=$3

if ! shift 3 &> /dev/null; then
	echo "usage: $(basename $0) <mode> <day> <part>"
	exit 1
fi

codesign -dvvv --entitlements=- "target/${mode}/day${day}_${part}"
